# Generated by Django 5.0.3 on 2024-06-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/medicine/'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
