# Generated by Django 5.0.3 on 2024-06-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_medication_image_prescription_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/medications/'),
        ),
    ]
