# Generated by Django 5.0.3 on 2024-06-10 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_alter_clinic_status'),
        ('hr', '0003_alter_employee_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.clinic'),
        ),
    ]
