# Generated by Django 5.0.3 on 2024-06-23 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CheckOut', 'CheckOut'), ('Booked', 'Booked'), ('Occupied', 'Occupied'), ('Empty', 'Empty')], default='Empty', max_length=13)),
                ('name', models.CharField(max_length=30)),
                ('disease', models.CharField(blank=True, max_length=30, null=True)),
                ('treatment', models.CharField(blank=True, max_length=30, null=True)),
                ('descrption', models.CharField(blank=True, max_length=100, null=True)),
                ('reserved_from', models.DateTimeField(blank=True, null=True)),
                ('reserved_until', models.DateTimeField(blank=True, null=True)),
                ('doctors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to=settings.AUTH_USER_MODEL)),
                ('nurses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurses', to=settings.AUTH_USER_MODEL)),
                ('patients', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Surgery', 'Surgery'), ('SingleRoom', 'SingleRoom'), ('MultiRoom', 'MultiRoom')], default='MultiRoom', max_length=13)),
                ('name', models.CharField(max_length=30)),
                ('maxNumber_inRoom', models.IntegerField(default=2)),
                ('number_in_room', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Occupied', 'Occupied'), ('Book', 'Book'), ('Full', 'Full'), ('Empty', 'Empty')], default='Empty', max_length=8)),
                ('incharge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_incharge', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Surgery', 'Surgery'), ('inPatient Treatment', 'inPatient Treatment')], max_length=20)),
                ('disease', models.CharField(blank=True, max_length=30, null=True)),
                ('treatment', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=7)),
                ('descrption', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(default='2024-06-23 21:36:30', max_length=30)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Beds_call', to='nurses.bed')),
                ('doctors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors_call', to=settings.AUTH_USER_MODEL)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurses_call', to=settings.AUTH_USER_MODEL)),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_call', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rooms_call', to='nurses.room')),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Room', to='nurses.room'),
        ),
    ]
