# Generated by Django 5.0.3 on 2024-06-05 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Surgery', 'Surgery'), ('SingleRoom', 'SingleRoom'), ('MultiRoom', 'MultiRoom')], default='MultiRoom', max_length=13)),
                ('name', models.CharField(max_length=30)),
                ('maxNumber_inRoom', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_room', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Occupied', 'Occupied'), ('Full', 'Full'), ('Booked', 'Booked'), ('Empty', 'Empty')], default='Empty', max_length=8)),
                ('disease', models.CharField(blank=True, max_length=30, null=True)),
                ('treatment', models.CharField(blank=True, max_length=30, null=True)),
                ('reserved_from', models.CharField(default='2024-06-05 23:59:26', max_length=30)),
                ('reserved_until', models.CharField(blank=True, max_length=30, null=True)),
                ('doctors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to=settings.AUTH_USER_MODEL)),
                ('incharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_incharge', to=settings.AUTH_USER_MODEL)),
                ('nurses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurses', to=settings.AUTH_USER_MODEL)),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='nurses.room')),
            ],
        ),
    ]
