# Generated by Django 5.0.3 on 2024-06-06 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Occupied', 'Occupied'), ('Empty', 'Empty')], default='MultiRoom', max_length=13)),
                ('name', models.CharField(max_length=30)),
                ('disease', models.CharField(blank=True, max_length=30, null=True)),
                ('treatment', models.CharField(blank=True, max_length=30, null=True)),
                ('descrption', models.CharField(max_length=100)),
                ('reserved_from', models.CharField(default='2024-06-06 16:10:23', max_length=30)),
                ('reserved_until', models.CharField(blank=True, max_length=30, null=True)),
                ('doctors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to=settings.AUTH_USER_MODEL)),
                ('nurses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurses', to=settings.AUTH_USER_MODEL)),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BedRoom', to='nurses.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_room', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Occupied', 'Occupied'), ('Book', 'Book'), ('Full', 'Full'), ('Empty', 'Empty')], default='Empty', max_length=8)),
                ('bed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nurses.bed')),
                ('incharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_incharge', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='nurses.room')),
            ],
        ),
        migrations.DeleteModel(
            name='RoomReservation',
        ),
    ]
