# Generated by Django 5.0.3 on 2024-06-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='reserved_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='calls',
            name='date',
            field=models.CharField(default='2024-06-11 11:35:32', max_length=30),
        ),
    ]
