# Generated by Django 5.0.3 on 2024-06-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='date',
            field=models.CharField(default='2024-06-09 20:43:51', max_length=30),
        ),
    ]
