# Generated by Django 5.0.3 on 2024-06-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0002_alter_calls_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='reserved_from',
            field=models.DateTimeField(default='06/10/2024 01:51'),
        ),
        migrations.AlterField(
            model_name='calls',
            name='date',
            field=models.DateTimeField(default='06/10/2024 01:51'),
        ),
    ]
