# Generated by Django 5.0.3 on 2024-06-06 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0002_bed_roomdetails_delete_roomreservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='descrption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bed',
            name='doctors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bed',
            name='nurses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bed',
            name='patients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bed',
            name='reserved_from',
            field=models.CharField(default='2024-06-06 17:55:40', max_length=30),
        ),
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.CharField(choices=[('Occupied', 'Occupied'), ('Empty', 'Empty')], default='Empty', max_length=13),
        ),
    ]
