# Generated by Django 5.0.3 on 2024-06-06 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0003_alter_bed_descrption_alter_bed_doctors_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_incharge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='number_in_room',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Occupied', 'Occupied'), ('Book', 'Book'), ('Full', 'Full'), ('Empty', 'Empty')], default='Empty', max_length=8),
        ),
        migrations.AlterField(
            model_name='bed',
            name='reserved_from',
            field=models.CharField(default='2024-06-06 18:20:41', max_length=30),
        ),
        migrations.AlterField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Room', to='nurses.room'),
        ),
        migrations.DeleteModel(
            name='RoomDetails',
        ),
    ]
