# Generated by Django 5.0.3 on 2024-06-06 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0004_room_incharge_room_number_in_room_room_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='reserved_from',
            field=models.CharField(default='2024-06-06 19:48:46', max_length=30),
        ),
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.CharField(choices=[('CheckOut', 'CheckOut'), ('Booked', 'Booked'), ('Occupied', 'Occupied'), ('Empty', 'Empty')], default='Empty', max_length=13),
        ),
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Surgery', 'Surgery'), ('inPatient Treatment', 'inPatient Treatment')], max_length=20)),
                ('disease', models.CharField(max_length=30)),
                ('treatment', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=7)),
                ('descrption', models.CharField(max_length=100)),
                ('date', models.CharField(default='2024-06-06 19:48:46', max_length=30)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Beds_call', to='nurses.bed')),
                ('doctors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors_call', to=settings.AUTH_USER_MODEL)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurses_call', to=settings.AUTH_USER_MODEL)),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_call', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Rooms_call', to='nurses.room')),
            ],
        ),
    ]
