# Generated by Django 5.0.3 on 2024-06-11 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0006_alter_bed_reserved_from_alter_calls_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_createdBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calls',
            name='date',
            field=models.CharField(default='2024-06-11 04:16:10', max_length=30),
        ),
    ]
