# Generated by Django 5.0.3 on 2024-06-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0009_alter_calls_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='disease',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
