# Generated by Django 5.0.3 on 2024-06-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0010_alter_calls_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='disease',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
