# Generated by Django 5.0.3 on 2024-06-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0011_alter_calls_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='descrption',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='calls',
            name='disease',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='calls',
            name='treatment',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
