# Generated by Django 5.0.3 on 2024-06-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses', '0012_alter_calls_descrption_alter_calls_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='descrption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='calls',
            name='disease',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='calls',
            name='treatment',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
