# Generated by Django 5.0.3 on 2024-04-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('forgot-password', 'forgot-password'), ('change-email', 'change-email'), ('register', 'register')], max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
