# Generated by Django 5.0.3 on 2024-04-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification_code', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='created_at',
            field=models.CharField(default=' 2024-04-23 18:48:28', max_length=30),
        ),
    ]
