# Generated by Django 5.0.2 on 2024-03-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification_code', '0002_alter_verificationcode_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
