# Generated by Django 5.0.2 on 2024-03-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification_code', '0004_alter_verificationcode_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='create_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
