# Generated by Django 5.0.2 on 2024-03-26 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification_code', '0006_alter_verificationcode_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationcode',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
