# Generated by Django 5.0.2 on 2024-03-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification_code', '0007_rename_create_at_verificationcode_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
