# Generated by Django 5.0.3 on 2024-04-06 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification_code', '0009_alter_verificationcode_code_and_more'),
        ('verification_code', '0009_alter_verificationcode_created_at'),
    ]

    operations = [
    ]
