# Generated by Django 5.0.3 on 2024-04-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification_code', '0010_merge_20240407_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='created_at',
            field=models.CharField(default=' 2024-04-06 22:05:17', max_length=30),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='type',
            field=models.CharField(choices=[('forgot-password', 'forgot-password'), ('change-email', 'change-email'), ('register', 'register')], max_length=15),
        ),
    ]
