# Generated by Django 5.0.2 on 2024-03-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('M', 'Maried'), ('S', 'Single'), ('W', 'widow'), ('D', 'devorced')], default='S', max_length=1),
        ),
    ]
