# Generated by Django 5.0.2 on 2024-03-07 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_remove_clinic_doctor_id_remove_workinghour_doctor_id_and_more'),
        ('patients', '0003_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.clinic'),
        ),
    ]
