# Generated by Django 5.0.2 on 2024-03-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_remove_clinic_doctor_id_remove_workinghour_doctor_id_and_more'),
        ('patients', '0007_reservations_number_in_qeue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='working_hour',
        ),
        migrations.AddField(
            model_name='reservations',
            name='clinic',
            field=models.ManyToManyField(blank=True, null=True, to='doctors.clinic'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='working_hour',
            field=models.ManyToManyField(blank=True, null=True, to='doctors.workinghour'),
        ),
    ]
