# Generated by Django 5.0.2 on 2024-03-08 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_remove_clinic_doctor_id_remove_workinghour_doctor_id_and_more'),
        ('patients', '0008_remove_reservations_clinic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='working_hour',
        ),
        migrations.AddField(
            model_name='reservations',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.clinic'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='working_hour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.workinghour'),
        ),
    ]
