# Generated by Django 5.0.2 on 2024-03-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_medicalhistory_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, choices=[('AnatomicalPathology', 'AnatomicalPathology'), ('Anesthesiology', 'Anesthesiology'), ('Cardiology', 'Cardiology'), ('Cardiovascular/ThoracicSurgery', 'Cardiovascular/ThoracicSurgery'), ('ClinicalImmunology/Allergy', 'ClinicalImmunology/Allergy'), ('CriticalCareMedicine', 'CriticalCareMedicine'), ('Dermatology', 'Dermatology'), ('DiagnosticRadiology', 'DiagnosticRadiology'), ('EmergencyMedicine', 'EmergencyMedicine'), ('EndocrinologyandMetabolism', 'EndocrinologyandMetabolism'), ('FamilyMedicine', 'FamilyMedicine'), ('Gastroenterology', 'Gastroenterology'), ('GeneralInternalMedicine', 'GeneralInternalMedicine'), ('GeneralSurgery', 'GeneralSurgery'), ('General/ClinicalPathology', 'General/ClinicalPathology'), ('GeriatricMedicine', 'GeriatricMedicine'), ('Hematology', 'Hematology'), ('MedicalBiochemistry', 'MedicalBiochemistry'), ('MedicalGenetics', 'MedicalGenetics'), ('MedicalMicrobiologyandInfectiousDiseases', 'MedicalMicrobiologyandInfectiousDiseases'), ('MedicalOncology', 'MedicalOncology'), ('Nephrology', 'Nephrology'), ('Neurology', 'Neurology'), ('Neurosurgery', 'Neurosurgery'), ('NuclearMedicine', 'NuclearMedicine'), ('Obstetrics/Gynecology', 'Obstetrics/Gynecology'), ('OccupationalMedicine', 'OccupationalMedicine'), ('Ophthalmology', 'Ophthalmology'), ('OrthopedicSurgery', 'OrthopedicSurgery'), ('Otolaryngology', 'Otolaryngology'), ('Pediatrics', 'Pediatrics'), ('PhysicalMedicineandRehabilitation', 'PhysicalMedicineandRehabilitation'), ('PlasticSurgery', 'PlasticSurgery'), ('Psychiatry', 'Psychiatry'), ('PublicHealthandPreventiveMedicine', 'PublicHealthandPreventiveMedicine'), ('RadiationOncology', 'RadiationOncology'), ('Respirology', 'Respirology'), ('Rheumatology', 'Rheumatology'), ('Urology', 'Urology')], max_length=50, null=True),
        ),
    ]
