# Generated by Django 5.0.2 on 2024-03-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_user_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blood',
            field=models.CharField(choices=[('O', 'O'), ('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], default='O+', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='national_card_number',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ssn',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(choices=[('AnatomicalPathology', 'AnatomicalPathology'), ('Anesthesiology', 'Anesthesiology'), ('Cardiology', 'Cardiology'), ('Cardiovascular/ThoracicSurgery', 'Cardiovascular/ThoracicSurgery'), ('ClinicalImmunology/Allergy', 'ClinicalImmunology/Allergy'), ('CriticalCareMedicine', 'CriticalCareMedicine'), ('Dermatology', 'Dermatology'), ('DiagnosticRadiology', 'DiagnosticRadiology'), ('EmergencyMedicine', 'EmergencyMedicine'), ('EndocrinologyandMetabolism', 'EndocrinologyandMetabolism'), ('FamilyMedicine', 'FamilyMedicine'), ('Gastroenterology', 'Gastroenterology'), ('GeneralInternalMedicine', 'GeneralInternalMedicine'), ('GeneralSurgery', 'GeneralSurgery'), ('General/ClinicalPathology', 'General/ClinicalPathology'), ('GeriatricMedicine', 'GeriatricMedicine'), ('Hematology', 'Hematology'), ('MedicalBiochemistry', 'MedicalBiochemistry'), ('MedicalGenetics', 'MedicalGenetics'), ('MedicalMicrobiologyandInfectiousDiseases', 'MedicalMicrobiologyandInfectiousDiseases'), ('MedicalOncology', 'MedicalOncology'), ('Nephrology', 'Nephrology'), ('Neurology', 'Neurology'), ('Neurosurgery', 'Neurosurgery'), ('NuclearMedicine', 'NuclearMedicine'), ('Obstetrics/Gynecology', 'Obstetrics/Gynecology'), ('OccupationalMedicine', 'OccupationalMedicine'), ('Ophthalmology', 'Ophthalmology'), ('OrthopedicSurgery', 'OrthopedicSurgery'), ('Otolaryngology', 'Otolaryngology'), ('Pediatrics', 'Pediatrics'), ('PhysicalMedicineandRehabilitation', 'PhysicalMedicineandRehabilitation'), ('PlasticSurgery', 'PlasticSurgery'), ('Psychiatry', 'Psychiatry'), ('PublicHealthandPreventiveMedicine', 'PublicHealthandPreventiveMedicine'), ('RadiationOncology', 'RadiationOncology'), ('Respirology', 'Respirology'), ('Rheumatology', 'Rheumatology'), ('Urology', 'Urology')], max_length=50, null=True),
        ),
    ]
