# Generated by Django 5.0.3 on 2024-03-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_user_blood_user_national_card_number_user_ssn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='insurance_number',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
