# Generated by Django 5.0.2 on 2024-03-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_user_insurance_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='national_card_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='insurance_number',
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ssn',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('P', 'Patient'), ('D', 'Doctor'), ('A', 'Admin'), ('N', 'Nurse'), ('H', 'Human Resources')], default='P', max_length=2),
        ),
    ]
