# Generated by Django 5.0.3 on 2024-04-06 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_workinghour_day'),
        ('patients', '0014_remove_user_national_card_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservations',
            new_name='Reservation',
        ),
    ]
