# Generated by Django 5.0.3 on 2024-04-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_rename_reservations_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('D', 'Done')], default='P', max_length=1),
        ),
    ]
