# Generated by Django 5.0.3 on 2024-04-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserved_at',
            field=models.CharField(default='2024-04-20 19:10:22', max_length=30),
        ),
    ]
