# Generated by Django 5.0.3 on 2024-04-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_reservation_price_reservation_reserved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment',
            field=models.CharField(default='Cash', max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_at',
            field=models.CharField(default='2024-04-20 20:07:09', max_length=30),
        ),
    ]
