# Generated by Django 5.0.3 on 2024-04-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_reservation_payment_alter_reservation_reserved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_at',
            field=models.CharField(default='2024-04-20 20:19:04', max_length=30),
        ),
    ]
