# Generated by Django 5.0.3 on 2024-04-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_reservation_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserved_at',
            field=models.CharField(default='2024-04-21 20:34:33', max_length=30),
        ),
    ]
