# Generated by Django 5.0.3 on 2024-05-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0038_reservation_type_alter_reservation_reserved_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='remember_card',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_at',
            field=models.CharField(default='2024-05-13 19:28:50', max_length=30),
        ),
    ]
