# Generated by Django 5.0.3 on 2024-05-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0042_alter_reservation_reserved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_at',
            field=models.CharField(default='2024-05-14 12:20:46', max_length=30),
        ),
    ]
