# Generated by Django 5.0.3 on 2024-05-14 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('patients', '0043_user_salary_alter_reservation_reserved_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.AddField(
            model_name='user',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_at',
            field=models.CharField(default='2024-05-14 14:58:37', max_length=30),
        ),
    ]
