# Generated by Django 5.0.3 on 2024-05-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0045_alter_reservation_reserved_at_alter_user_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserved_at',
            field=models.CharField(default='2024-05-14 16:04:11', max_length=30),
        ),
    ]
