# Generated by Django 5.0.3 on 2024-06-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0069_alter_reservation_reserved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/medical_records/'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_at',
            field=models.CharField(default='2024-06-09 18:27:08', max_length=30),
        ),
    ]
