# Generated by Django 5.0.3 on 2024-06-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0070_alter_medicalrecord_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserved_at',
            field=models.CharField(default='2024-06-10 04:21:58', max_length=30),
        ),
    ]
