# Generated by Django 5.0.3 on 2024-06-10 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0049_alter_reservation_reserved_at_alter_user_employee'),
        ('patients', '0072_alter_reservation_reserved_at_alter_user_employee'),
    ]

    operations = [
    ]
