# Generated by Django 5.0.3 on 2024-06-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0072_alter_reservation_reserved_at_alter_user_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserved_at',
            field=models.CharField(default='2024-06-11 11:35:32', max_length=30),
        ),
    ]
