# Generated by Django 5.0.3 on 2024-06-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0073_merge_20240610_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserved_at',
            field=models.CharField(default='2024-06-10 23:58:40', max_length=30),
        ),
    ]
