# Generated by Django 5.0.2 on 2024-03-07 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_rename_workinghours_workinghour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='workinghour',
            name='doctor_id',
        ),
        migrations.AddField(
            model_name='workinghour',
            name='clinic_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.clinic'),
        ),
    ]
