# Generated by Django 5.0.3 on 2024-04-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_workinghour_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('C', 'Canceled')], default='A', max_length=1),
        ),
    ]
