# Generated by Django 5.0.3 on 2024-04-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_clinic_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='price',
            field=models.FloatField(default=100),
        ),
    ]
