# Generated by Django 5.0.3 on 2024-06-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_clinic_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('C', 'Closed')], default='A', max_length=1),
        ),
    ]
